In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import  mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv("movie_metadata.csv")
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [3]:
df.nunique()

color                           2
director_name                2398
num_critic_for_reviews        528
duration                      191
director_facebook_likes       435
actor_3_facebook_likes        906
actor_2_name                 3032
actor_1_facebook_likes        878
gross                        4035
genres                        914
actor_1_name                 2097
movie_title                  4917
num_voted_users              4826
cast_total_facebook_likes    3978
actor_3_name                 3521
facenumber_in_poster           19
plot_keywords                4760
movie_imdb_link              4919
num_user_for_reviews          954
language                       46
country                        65
content_rating                 18
budget                        439
title_year                     91
actor_2_facebook_likes        917
imdb_score                     78
aspect_ratio                   22
movie_facebook_likes          876
dtype: int64

In [4]:
columns_to_drop = ['color', 'movie_imdb_link', 'facenumber_in_poster', 'movie_title' ,'plot_keywords','actor_3_name','aspect_ratio','language']
df = df.drop(columns=columns_to_drop)
df

,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,num_voted_users,cast_total_facebook_likes,num_user_for_reviews,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes
0,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,886204,4834,3054.0,USA,PG-13,237000000.0,2009.0,936.0,7.9,33000
1,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,471220,48350,1238.0,USA,PG-13,300000000.0,2007.0,5000.0,7.1,0
2,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,275868,11700,994.0,UK,PG-13,245000000.0,2015.0,393.0,6.8,85000
3,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,1144337,106759,2701.0,USA,PG-13,250000000.0,2012.0,23000.0,8.5,164000
4,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,8,143,NaN,NaN,NaN,NaN,NaN,12.0,7.1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,Eric Mabius,629,2283,6.0,Canada,NaN,NaN,2013.0,470.0,7.7,84
5039,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,73839,1753,359.0,USA,TV-14,NaN,NaN,593.0,7.5,32000
5040,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,Eva Boehnke,38,0,3.0,USA,NaN,1400.0,2013.0,0.0,6.3,16
5041,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,Alan Ruck,1255,2386,9.0,USA,PG-13,NaN,2012.0,719.0,6.3,660
5042,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,John August,4285,163,84.0,USA,PG,1100.0,2004.0,23.0,6.6,456

In [5]:
df.dtypes

director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
num_voted_users                int64
cast_total_facebook_likes      int64
num_user_for_reviews         float64
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
movie_facebook_likes           int64
dtype: object

In [6]:
# Convert categorical variables using LabelEncoder
label_encoder = LabelEncoder()
categorical_columns = ['director_name', 'actor_2_name', 'actor_1_name', 'genres', 'country', 'content_rating']
for col in categorical_columns:
    df[col] = label_encoder.fit_transform(df[col])

# Apply log transformation to numerical columns
numerical_columns = ['director_name', 'actor_2_name', 'actor_1_name', 'genres', 'country', 'content_rating','num_critic_for_reviews', 'duration', 'director_facebook_likes', 
                     'actor_3_facebook_likes', 'actor_1_facebook_likes', 'gross', 
                     'num_voted_users', 'cast_total_facebook_likes', 'num_user_for_reviews', 
                     'budget', 'title_year', 'actor_2_facebook_likes', 'imdb_score', 'movie_facebook_likes']

# Add a small constant to avoid log(0)
df[numerical_columns] = df[numerical_columns].apply(lambda x: x + 1e-6).apply(np.log)

# Now df contains your transformed data
df= df.dropna()
df

,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,num_voted_users,cast_total_facebook_likes,num_user_for_reviews,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes
0,6.826545,6.583409,5.181784,-13.815511,6.751101,7.247793,6.907755,20.449494,4.663439,5.575949,13.694702,8.483430,8.024207,4.127134,1.945910,19.283571,7.605392,6.841615,2.066863,10.404263
1,6.677083,5.710427,5.129899,6.333280,6.907755,7.703459,10.596635,19.550159,4.605170,6.883463,13.063080,10.786222,7.121252,4.127134,1.945910,19.519293,7.604396,8.517193,1.960095,-13.815511
2,7.611348,6.400257,4.997212,-13.815511,5.081404,7.818832,9.305651,19.114199,4.844187,5.855072,12.527678,9.367344,6.901737,4.110874,1.945910,19.316769,7.608374,5.973810,1.916923,11.350407
3,5.921578,6.700731,5.099866,9.998798,10.043249,6.276643,10.203592,19.920595,5.659482,7.582229,13.950336,11.578329,7.901377,4.127134,1.945910,19.336971,7.606885,10.043249,2.140066,12.007622
5,4.595120,6.135565,4.882802,6.163315,6.272877,7.842279,6.461468,18.106773,4.828314,6.079933,12.265303,7.535297,6.603944,4.127134,1.945910,19.390323,7.606885,6.448889,1.887070,10.085809
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,7.633854,4.962845,4.343805,5.673323,2.079442,6.579251,5.673323,12.959280,6.751101,7.495542,11.193257,5.908083,5.916202,4.127134,1.945910,8.853665,7.602900,3.806663,1.945910,9.852194
5034,7.412160,3.555348,4.382027,-13.815511,-13.815511,6.741701,-13.815511,11.157264,6.813445,6.622736,6.378426,-13.815511,3.555348,3.828641,1.609438,8.853665,7.603399,-13.815511,1.840550,4.304065
5035,7.573017,4.025352,4.394449,-13.815511,1.791760,7.741534,4.795791,14.528911,5.308268,5.616771,10.860056,4.990433,4.867534,4.127134,2.197225,8.853665,7.596894,2.995732,1.931522,-13.815511
5037,6.434547,2.639057,4.553877,-13.815511,4.890349,6.061457,5.690359,8.430327,6.405228,6.993015,7.198931,6.536692,2.639057,4.127134,1.609438,9.104980,7.606387,5.323010,1.856298,6.023448
5042,7.054450,3.761200,4.499810,2.772589,2.772589,5.934894,4.454347,11.353015,6.624065,6.853299,8.362876,5.093750,4.430817,4.127134,1.791760,7.003065,7.602900,3.135494,1.887070,6.122493

In [7]:
# Split the data into features (X) and movie rating variable (y)
X = df.drop(columns=['imdb_score'])
y = df['imdb_score']

# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
# Calculate Mean Absolute Percentage Error (MAPE)
def mape(y_true, y_pred):
    return np.mean(np.abs((y_pred-y_true) / y_true)) * 100

In [9]:
# Initialize the linear regression model
model = LinearRegression()

# Fit the model on the training data
model.fit(X_train, y_train)

# Predict the target variable on the test data
y_pred = model.predict(X_test)



# Predictions on training and testing data
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)


linear_train = np.sqrt(mean_squared_error(y_train, y_train_pred))
linear_test = np.sqrt(mean_squared_error(y_test, y_test_pred))

# Evaluate the model accuracy using R-squared score
print("train data (R-squared score):",model.score(X_train, y_train))
print("test data (R-squared score):",model.score(X_test, y_test))


# Calculate RMSE for training and testing data
rmse_train = np.sqrt(mean_squared_error(y_train, y_train_pred))
rmse_test = np.sqrt(mean_squared_error(y_test, y_test_pred))

print("RMSE on training data:", rmse_train)
print("RMSE on testing data:", rmse_test)

# Calculate MAPE for training and testing data
mape_train = mape(y_train, y_train_pred)
mape_test = mape(y_test, y_test_pred)

print("MAPE on training data:", mape_train)
print("MAPE on testing data:", mape_test)

# Display accuracy
accuracy_train = 100 - mape_train
accuracy_test = 100 - mape_test

print("Accuracy on training data:", accuracy_train)
print("Accuracy on testing data:", accuracy_test)

train data (R-squared score): 0.369190589992232
test data (R-squared score): 0.37319003476824464
RMSE on training data: 0.15047344826764236
RMSE on testing data: 0.13285336126361524
MAPE on training data: 6.248294120129635
MAPE on testing data: 5.608407968184351
Accuracy on training data: 93.75170587987037
Accuracy on testing data: 94.39159203181565

In [10]:
dt_model = DecisionTreeRegressor(random_state=42)

# Fit Decision Tree models on the training data
dt_model.fit(X_train, y_train)

y_train_pred_dt = dt_model.predict(X_train)
y_test_pred_dt = dt_model.predict(X_test)

# Evaluate Decision Tree model
r2_dt_train = dt_model.score(X_train, y_train)
r2_dt_test = dt_model.score(X_test, y_test)

rmse_dt_train = np.sqrt(mean_squared_error(y_train, y_train_pred_dt))
rmse_dt_test = np.sqrt(mean_squared_error(y_test, y_test_pred_dt))

mape_dt_train = 100-mape(y_train, y_train_pred_dt)
mape_dt_test = 100-mape(y_test, y_test_pred_dt)
print("Decision Tree Model:")
# Evaluate the model accuracy using R-squared score

print("R-squared (Train):", r2_dt_train)
print("R-squared (Test):", r2_dt_test)
print("RMSE (Train):", rmse_dt_train)
print("RMSE (Test):", rmse_dt_test)
print("Accuracy(Train):", mape_dt_train)
print("Accuracy (Test):", mape_dt_test)

Decision Tree Model:
R-squared (Train): 1.0
R-squared (Test): -0.1417438383993923
RMSE (Train): 2.3582147957273754e-17
RMSE (Test): 0.17930357092243981
Accuracy(Train): 100.0
Accuracy (Test): 93.1681622117587

In [11]:
# Initialize Random Forest 
rf_model = RandomForestRegressor()


# Fit Random Forest  models on the training data
rf_model.fit(X_train, y_train)


# Predictions on training and testing data for Random Forest model
y_train_pred_rf = rf_model.predict(X_train)
y_test_pred_rf = rf_model.predict(X_test)


# Evaluate Random Forest model
r2_rf_train = rf_model.score(X_train, y_train)
r2_rf_test = rf_model.score(X_test, y_test)

rmse_rf_train = np.sqrt(mean_squared_error(y_train, y_train_pred_rf))
rmse_rf_test = np.sqrt(mean_squared_error(y_test, y_test_pred_rf))

mae_rf_train = mean_absolute_error(y_train, y_train_pred_rf)
mae_rf_test = mean_absolute_error(y_test, y_test_pred_rf)

mape_rf_train = 100-mape(y_train, y_train_pred_rf)
mape_rf_test = 100-mape(y_test, y_test_pred_rf)

# Display results
print("Random Forest Model:")
print("R-squared (Train):", r2_rf_train)
print("R-squared (Test):", r2_rf_test)
print("RMSE (Train):", rmse_rf_train)
print("RMSE (Test):", rmse_rf_test)
print("Accuracy(Train):", mape_rf_train)
print("Accuracy(Test):", mape_rf_test)

Random Forest Model:
R-squared (Train): 0.9290865526669017
R-squared (Test): 0.5116832640309084
RMSE (Train): 0.05045161709724612
RMSE (Test): 0.11726148912806796
Accuracy(Train): 97.97506095864362
Accuracy(Test): 95.26041797355423